### ISSUE TITLE
Milestone 1: Discussion

### ISSUE THREAD

**Issue by mel-liow** [UBC-MDS/gapminder_dashboard#1]
- [X] [Work Contract](https://docs.google.com/document/d/1RvCkJh0H2MJ3HW2e7yCfJaqaQIkd-8RyAbwm8yIRoUg/edit)

Dataset: Gapminder

Section 1: Arijeet
Section 2: Anupriya
Section 3: Mel
Section 4: Reza

**Comment by arijeetchatterjee** [comment]
All activities for Milestone 1 completed.
