### ISSUE TITLE
Research questions and usage scenarios

### ISSUE THREAD

**Issue by mel-liow** [UBC-MDS/gapminder_dashboard#2]
- [x] Brief persona description
- [x] User story
- [x] Indicate tasks in brackets
- [x] Hypothetical walkthrough of the application

**Comment by mel-liow** [comment]
What are everyone’s thoughts about tailoring our dashboard to be an educational tool rather than something “research” focus? 
I.e. our audience will be teachers/ students

**Comment by Anupriya-Sri** [comment]
I think that is a good idea. It will be more specific rather than a generic application.
